import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.overview': 'Executive Overview',
    'nav.sectoral': 'Sectoral Analysis',
    'nav.lastmile': 'Last-Mile Analytics',
    'nav.transparency': 'Data Transparency',
    'nav.policy': 'Policy Impact',
    'app.title': 'Smart Observatory',
    'app.subtitle': 'Digital Platform Workers',
    'search.placeholder': 'Search metrics, sectors...',
    'settings': 'Settings',
    'lastmile.title': 'Last-Mile Analytics',
    'lastmile.subtitle': 'Traffic, POI, and workforce density analysis.',
    'filter.allday': 'All Day',
    'filter.peakhours': 'Peak Hours',
    'filter.offpeakhours': 'Off-Peak Hours',
    'overview.title': 'Executive Overview',
    'overview.subtitle': 'Real-time estimation of the Gig Economy workforce.',
    'filter.last30days': 'Last 30 Days',
    'filter.thisquarter': 'This Quarter',
    'filter.yeartodate': 'Year to Date',
    'export.report': 'Export Report',
    'kpi.totalworkers': 'Total Estimated Workers',
    'kpi.vslastmonth': 'vs last month',
    'kpi.sectorbreakdown': 'Sector Breakdown',
    'sector.delivery': 'Delivery',
    'sector.transport': 'Transport',
    'sector.freelance': 'Freelance',
    'kpi.coveragegap': 'Coverage Gap',
    'kpi.unregistered': 'unregistered workers',
    'kpi.marketvitality': 'Market Vitality Index',
    'kpi.basedonsearch': 'Composite score based on search volume, app updates, and new profile creations.',
    'chart.vitality.title': 'Market Vitality Trends',
    'chart.vitality.subtitle': 'Correlation between search interest, app updates, and profile growth.',
    'chart.gap.title': 'Official vs Digital Reality',
    'chart.gap.subtitle': 'Discrepancy between registered workers and digital footprint estimates.',
    'map.title': 'Geographic Density',
    'map.subtitle': 'Live workforce distribution across major cities.',
    'map.filter.all': 'All Sectors',
    'sectoral.title': 'Sectoral Analysis',
    'sectoral.subtitle': 'Deep dive into specific gig economy sectors.',
    'chart.review.title': 'The "Review Footprint" Model',
    'chart.review.subtitle': 'Correlation between new app reviews and estimated active workers.',
    'chart.skill.title': 'Freelance Skill Demand vs. Supply',
    'chart.skill.subtitle': 'Analyzing the gap between market demand and available talent.',
    'chart.trend.title': 'Sector Growth Projections',
    'chart.trend.subtitle': 'Estimated shift in gig economy composition over time.',
    'transparency.title': 'Data Source Transparency',
    'transparency.subtitle': 'The "Engine" View: Monitor data streams and methodologies.',
    'button.forcesync': 'Force Sync All',
    'table.source': 'Data Source',
    'table.status': 'Status',
    'table.lastsync': 'Last Sync',
    'table.datatype': 'Data Type',
    'table.records': 'Records Processed',
    'status.healthy': 'Healthy',
    'status.degraded': 'Degraded',
    'status.failed': 'Failed',
    'methodology.title': 'Methodology',
    'methodology.subtitle': 'Estimation logic.',
    'button.viewformula': 'View Mathematical Formula',
    'formula.title': 'The "Review Footprint" Model',
    'formula.desc': 'Our primary estimation engine relies on the assumption that a predictable percentage of active gig workers leave app reviews or search for specific platform-related terms. By tracking these public digital footprints and applying a multiplier derived from periodic ground-truth surveys, we can estimate the total active workforce in real-time without relying on delayed administrative data.',
    'policy.title': 'Policy Impact & Simulations',
    'policy.subtitle': 'Design targeted protection programs and monitor crisis response.',
    'button.entercrisis': 'Enter Crisis Simulation',
    'button.exitcrisis': 'Exit Crisis Simulation',
    'chart.insurance.title': 'Insurance Gap Tracker',
    'chart.insurance.subtitle': 'Workers missing from social insurance systems.',
    'chart.insurance.gap': 'Gap',
    'chart.insurance.insured': 'Insured (Official)',
    'chart.insurance.uninsured': 'Uninsured Gap',
    'alert.vulnerable': 'Vulnerable Cohort Identified',
    'alert.vulnerable.desc': 'Est. 120k delivery drivers lack basic health coverage in high-density urban zones.',
    'chart.crisis.title': 'Crisis Response Simulation',
    'chart.crisis.subtitle': 'Simulated workforce shift during a major disruption (e.g., pandemic, fuel crisis).',
    'insight.crisis': 'Simulation Insight',
    'insight.crisis.desc': 'During a simulated lockdown event, transport sector drops by 60% while delivery surges by 150%. This requires immediate policy intervention to protect delivery workers from overexposure.',
    'button.generateproposal': 'Generate Protection Proposal',
    'crisis.pandemic': 'Pandemic Simulation (Lockdown Scenario)',
    'crisis.historical': 'Historical view of how the flexible market fluctuates during economic or health crises.',
    'crisis.simulated': 'Simulated shift in gig economy sectors during a severe mobility restriction event.',
    'crisis.active': 'Simulation Active',
    'crisis.transport.desc': 'Mobility collapse',
    'crisis.delivery.desc': 'Essential service surge',
    'crisis.freelance.desc': 'Remote work transition',
    // Google Trends
    'nav.trends': 'Google Trends',
    'trends.title': 'Google Trends Insights',
    'trends.subtitle': 'Real-time search trend analysis for gig economy keywords via Google Trends.',
    'trends.settings': 'Settings',
    'trends.run': 'Run Analysis',
    'trends.running': 'Running...',
    'trends.keywords': 'Search Keywords',
    'trends.addKeyword': 'Add a keyword...',
    'trends.region': 'Geographic Region',
    'trends.timeRange': 'Time Range',
    'trends.progressNote': 'Analysis typically takes 2-5 minutes. The Apify scraper is fetching data from Google Trends.',
    'trends.error': 'Analysis Failed',
    'trends.lastUpdated': 'Last updated',
    'trends.keywordsAnalyzed': 'keywords analyzed',
    'trends.noData': 'No data available',
    'trends.empty.title': 'No Analysis Results Yet',
    'trends.empty.desc': 'Configure your keywords, select a region, and run an analysis to see real Google Trends data for gig economy search patterns.',
    'trends.configureAndRun': 'Configure & Run Analysis',
    'trends.tab.scores': 'Trend Scores',
    'trends.tab.regions': 'Top Regions',
    'trends.tab.queries': 'Top Queries',
    'trends.tab.rising': 'Rising Queries',
    'trends.tab.intent': 'Work Intent',
    'trends.scores.title': 'Keyword Trend Scores',
    'trends.scores.desc': 'Average search interest index (0-100) per keyword.',
    'trends.scores.label': 'Trend Score',
    'trends.scores.table': 'Rankings',
    'trends.regions.title': 'Interest by Region',
    'trends.regions.desc': 'Search interest distribution across sub-regions.',
    'trends.regions.allKeywords': 'All Keywords',
    'trends.regions.keyword': 'Keyword',
    'trends.regions.regionName': 'Region',
    'trends.regions.score': 'Score',
    'trends.queries.title': 'Top Related Queries',
    'trends.queries.desc': 'Most popular related search queries.',
    'trends.queries.keyword': 'Keyword',
    'trends.queries.query': 'Related Query',
    'trends.queries.score': 'Score',
    'trends.rising.title': 'Rising & Breakout Queries',
    'trends.rising.desc': 'Queries with the biggest increase in search frequency.',
    'trends.rising.keyword': 'Keyword',
    'trends.rising.query': 'Rising Query',
    'trends.rising.growth': 'Growth',
    'trends.intent.title': 'Google Work Intent Analysis',
    'trends.intent.desc': 'Composite intent scoring based on search volume and related query depth.',
    'trends.intent.keyword': 'Keyword',
    'trends.intent.searchResults': 'Search Data Points',
    'trends.intent.relatedCount': 'Related Queries',
    'trends.intent.score': 'Intent Score',
    'trends.intent.topRelated': 'Top Related Queries',
    'trends.intent.scoreChart': 'Intent Score by Keyword',
    'trends.intent.relatedChart': 'Related Query Count by Keyword',
    // KPI Cards
    'trends.kpi.topKeyword': 'Top Trending Keyword',
    'trends.kpi.searchIndex': 'search interest index',
    'trends.kpi.topRegion': 'Dominant Region',
    'trends.kpi.aggregateScore': 'aggregate interest score',
    'trends.kpi.risingSignals': 'Rising Signals',
    'trends.kpi.noBreakout': 'No breakout queries detected',
    'trends.kpi.highestIntent': 'Highest Work Intent',
    'trends.kpi.intentScore': 'composite intent score',
    // Auto Insights
    'trends.keyInsights': 'Key Insights',
    'trends.insight.dominant': 'Dominant Search',
    'trends.insight.dominantDesc': 'leads all keywords with a search interest index of',
    'trends.insight.breakout': 'Breakout Alert',
    'trends.insight.breakoutDesc': 'breakout queries detected — rapid growth signals:',
    'trends.insight.regional': 'Regional Hotspot',
    'trends.insight.regionalDesc': 'shows the highest aggregate search activity across all tracked keywords.',
    'trends.insight.intent': 'Work Intent Leader',
    'trends.insight.intentDesc': 'shows the highest composite work intent score of',
    'trends.insight.coverage': 'Analysis Coverage',
    'trends.insight.coverageDesc1': 'keywords tracked',
    'trends.insight.coverageDesc2': 'related queries found',
    'trends.insight.coverageDesc3': 'active sub-regions',
    // App Store
    'nav.appstore': 'App Store Analytics',
    'apps.title': 'App Store & Google Play Insights',
    'apps.subtitle': 'Real-time gig economy platform analytics from App Store and Google Play reviews.',
    'apps.fetch': 'Fetch Store Data',
    'apps.fetching': 'Fetching...',
    'apps.loading': 'Fetching from App Store & Google Play...',
    'apps.loadingDesc': 'Querying iTunes Lookup API and Google Play for review counts.',
    'apps.params.title': 'Estimation Parameters',
    'apps.params.reviewRate': 'Review Writing Rate (%)',
    'apps.params.ordersPerDriver': 'Avg Orders per Driver / Day',
    'apps.params.activeRatio': 'Active Driver Ratio (%)',
    'apps.params.disclaimer': 'Estimates are based on configurable assumptions — not official figures. Adjust parameters to explore scenarios.',
    'apps.empty.ios': 'iOS review counts from iTunes Lookup API',
    'apps.empty.android': 'Android review counts from Google Play',
    'apps.empty.estimation': 'Driver Estimation',
    'apps.empty.estimationDesc': 'Estimate active drivers using configurable parameters',
    'apps.empty.desc': 'Click Fetch Store Data to pull live review counts and generate workforce estimates.',
    'apps.kpi.totalReviews': 'Total Reviews',
    'apps.kpi.acrossStores': 'Across all platforms',
    'apps.kpi.activeDrivers': 'Est. Active Drivers',
    'apps.kpi.atRatio': 'at active ratio',
    'apps.kpi.topPlatform': 'Market Leader',
    'apps.kpi.marketShare': 'of total reviews',
    'apps.kpi.iosShare': 'Avg iOS Share',
    'apps.kpi.iosDesc': 'For platforms with iOS data',
    'apps.chart.reviewsByPlatform': 'Reviews by Platform',
    'apps.chart.reviewsByPlatformDesc': 'iOS vs Android review distribution per app.',
    'apps.chart.activeDrivers': 'Estimated Active Drivers',
    'apps.chart.activeDriversDesc': 'Driver workforce estimate per platform.',
    'apps.chart.reviewDist': 'Review Distribution',
    'apps.chart.reviewDistDesc': 'Total review share across gig platforms.',
    'apps.keyInsights': 'Key Insights',
    'apps.insight.leader': 'Market Leader',
    'apps.insight.leaderDesc': 'leads with',
    'apps.insight.reviews': 'reviews',
    'apps.insight.share': 'market share',
    'apps.insight.android': 'Android Dominance',
    'apps.insight.androidDesc': 'platforms have more Android reviews than iOS',
    'apps.insight.ios': 'iOS Presence',
    'apps.insight.iosDesc': 'Average iOS share across platforms is',
    'apps.insight.iosApps': 'platforms have iOS data',
    'apps.insight.workforce': 'Workforce Estimate',
    'apps.insight.workforceDesc': 'Estimated total active gig workers:',
    'apps.insight.activeDrivers': 'across all platforms',
    'apps.table.title': 'Platform Data',
    'apps.table.desc': 'Detailed review counts and driver estimates per platform.',
    'apps.table.app': 'Platform',
    'apps.table.total': 'Total',
    'apps.table.transactions': 'Est. Transactions',
    'apps.table.drivers': 'Est. Drivers',
    'apps.table.active': 'Active',
    'apps.table.totals': 'TOTALS',
    // AI Analyst & Widget
    'nav.aianalyst': 'AI Analyst',
    'ai.title': 'AI Policy Analyst',
    'ai.subtitle': 'Ask questions about gig economy data, market trends, and policy implications.',
    'nav.salla': 'E-Commerce (Salla)',
    'salla.title': 'E-Commerce Ecosystem (Salla)',
    'salla.subtitle': 'Monitor platform growth and commercial registrations.',
    'ai.chat.placeholder': 'Ask me anything about the Saudi gig economy...',
    'ai.chat.send': 'Send',
    'ai.chat.typing': 'AI is thinking...',
    'ai.widget.title': 'Smart Assistant',
    'ai.error': 'Failed to communicate with AI.',
    'nav.aqar': 'Aqar Intelligence',
    'aqar.title': 'Aqar Intelligence: Airbnb Saudi Insights',
    'aqar.subtitle': 'Strategic analytics for short-term rental listings across the Kingdom.',
    'aqar.kpi.listings': 'Total Listings',
    'aqar.kpi.hosts': 'Total Hosts',
    'aqar.kpi.superhosts': 'Superhost Ratio',
    'aqar.kpi.avgPrice': 'Avg Nightly Price',
    'aqar.sync': 'Sync Intelligence',
    // Maroof Registry
    'nav.maroof': 'Maroof Registry',
    'maroof.title': 'Maroof Registry Intelligence',
    'maroof.subtitle': 'Saudi e-commerce store analytics from the Ministry of Commerce registry.',
    'maroof.sync': 'Sync Intelligence',
    'maroof.kpi.totalStores': 'Total Listed',
    'maroof.kpi.goldStores': 'Gold (CR)',
    'maroof.kpi.silverStores': 'Silver (FL)',
    'maroof.kpi.avgRating': 'Avg Rating',
    'maroof.chart.categories': 'Category Distribution',
    'maroof.chart.categoriesSub': 'Store count by business type',
    'maroof.chart.certification': 'Certification Breakdown',
    'maroof.chart.certificationSub': 'Gold vs Silver registration',
  },
  ar: {
    'nav.overview': 'نظرة عامة تنفيذية',
    'nav.sectoral': 'التحليل القطاعي',
    'nav.lastmile': 'تحليلات الميل الأخير',
    'nav.transparency': 'شفافية البيانات',
    'nav.policy': 'تأثير السياسات',
    'app.title': 'المرصد الذكي',
    'app.subtitle': 'عمال المنصات الرقمية',
    'search.placeholder': 'البحث في المقاييس، القطاعات...',
    'settings': 'الإعدادات',
    'lastmile.title': 'تحليلات الميل الأخير',
    'lastmile.subtitle': 'تحليل حركة المرور والنقاط المهمة وكثافة القوى العاملة.',
    'filter.allday': 'طوال اليوم',
    'filter.peakhours': 'ساعات الذروة',
    'filter.offpeakhours': 'خارج ساعات الذروة',
    'overview.title': 'نظرة عامة تنفيذية',
    'overview.subtitle': 'تقدير في الوقت الفعلي للقوى العاملة في اقتصاد العمل الحر.',
    'filter.last30days': 'آخر 30 يومًا',
    'filter.thisquarter': 'هذا الربع',
    'filter.yeartodate': 'منذ بداية العام',
    'export.report': 'تصدير التقرير',
    'kpi.totalworkers': 'إجمالي العمال المقدر',
    'kpi.vslastmonth': 'مقارنة بالشهر الماضي',
    'kpi.sectorbreakdown': 'توزيع القطاعات',
    'sector.delivery': 'التوصيل',
    'sector.transport': 'النقل',
    'sector.freelance': 'العمل الحر',
    'kpi.coveragegap': 'فجوة التغطية',
    'kpi.unregistered': 'عمال غير مسجلين',
    'kpi.marketvitality': 'مؤشر حيوية السوق',
    'kpi.basedonsearch': 'درجة مركبة تعتمد على حجم البحث وتحديثات التطبيقات وإنشاء ملفات تعريف جديدة.',
    'chart.vitality.title': 'اتجاهات حيوية السوق',
    'chart.vitality.subtitle': 'الارتباط بين الاهتمام بالبحث وتحديثات التطبيقات ونمو الملفات الشخصية.',
    'chart.gap.title': 'الواقع الرسمي مقابل الرقمي',
    'chart.gap.subtitle': 'التفاوت بين العمال المسجلين وتقديرات البصمة الرقمية.',
    'map.title': 'الكثافة الجغرافية',
    'map.subtitle': 'توزيع القوى العاملة المباشر عبر المدن الرئيسية.',
    'map.filter.all': 'جميع القطاعات',
    'sectoral.title': 'التحليل القطاعي',
    'sectoral.subtitle': 'تعمق في قطاعات محددة في اقتصاد العمل الحر.',
    'chart.review.title': 'نموذج "بصمة المراجعة"',
    'chart.review.subtitle': 'الارتباط بين مراجعات التطبيقات الجديدة والعمال النشطين المقدرين.',
    'chart.skill.title': 'الطلب على مهارات العمل الحر مقابل العرض',
    'chart.skill.subtitle': 'تحليل الفجوة بين طلب السوق والمواهب المتاحة.',
    'chart.trend.title': 'توقعات نمو القطاع',
    'chart.trend.subtitle': 'التحول المقدر في تكوين اقتصاد العمل الحر بمرور الوقت.',
    'transparency.title': 'شفافية مصدر البيانات',
    'transparency.subtitle': 'عرض "المحرك": مراقبة تدفقات البيانات والمنهجيات.',
    'button.forcesync': 'فرض مزامنة الكل',
    'table.source': 'مصدر البيانات',
    'table.status': 'الحالة',
    'table.lastsync': 'آخر مزامنة',
    'table.datatype': 'نوع البيانات',
    'table.records': 'السجلات المعالجة',
    'status.healthy': 'سليم',
    'status.degraded': 'متدهور',
    'status.failed': 'فشل',
    'methodology.title': 'المنهجية',
    'methodology.subtitle': 'منطق التقدير.',
    'button.viewformula': 'عرض الصيغة الرياضية',
    'formula.title': 'نموذج "بصمة المراجعة"',
    'formula.desc': 'يعتمد محرك التقدير الأساسي لدينا على افتراض أن نسبة يمكن التنبؤ بها من عمال العمل الحر النشطين يتركون مراجعات للتطبيقات أو يبحثون عن مصطلحات محددة متعلقة بالمنصة. من خلال تتبع هذه البصمات الرقمية العامة وتطبيق مضاعف مستمد من استطلاعات الحقيقة الأرضية الدورية، يمكننا تقدير إجمالي القوى العاملة النشطة في الوقت الفعلي دون الاعتماد على البيانات الإدارية المتأخرة.',
    'policy.title': 'تأثير السياسات والمحاكاة',
    'policy.subtitle': 'تصميم برامج حماية مستهدفة ومراقبة الاستجابة للأزمات.',
    'button.entercrisis': 'الدخول في محاكاة الأزمة',
    'button.exitcrisis': 'الخروج من محاكاة الأزمة',
    'chart.insurance.title': 'متتبع فجوة التأمين',
    'chart.insurance.subtitle': 'العمال المفقودون من أنظمة التأمين الاجتماعي.',
    'chart.insurance.gap': 'فجوة',
    'chart.insurance.insured': 'مؤمن عليه (رسمي)',
    'chart.insurance.uninsured': 'فجوة غير مؤمن عليهم',
    'alert.vulnerable': 'تم تحديد مجموعة ضعيفة',
    'alert.vulnerable.desc': 'ما يقدر بنحو 120 ألف سائق توصيل يفتقرون إلى التغطية الصحية الأساسية في المناطق الحضرية عالية الكثافة.',
    'chart.crisis.title': 'محاكاة الاستجابة للأزمات',
    'chart.crisis.subtitle': 'تحول القوى العاملة المحاكى أثناء اضطراب كبير (مثل الوباء، أزمة الوقود).',
    'insight.crisis': 'رؤية المحاكاة',
    'insight.crisis.desc': 'أثناء حدث الإغلاق المحاكى، ينخفض قطاع النقل بنسبة 60٪ بينما يرتفع قطاع التوصيل بنسبة 150٪. وهذا يتطلب تدخلاً سياسياً فورياً لحماية عمال التوصيل من التعرض المفرط.',
    'button.generateproposal': 'إنشاء مقترح حماية',
    'crisis.pandemic': 'محاكاة الوباء (سيناريو الإغلاق)',
    'crisis.historical': 'نظرة تاريخية لكيفية تقلب السوق المرن أثناء الأزمات الاقتصادية أو الصحية.',
    'crisis.simulated': 'تحول محاكى في قطاعات اقتصاد العمل الحر أثناء حدث تقييد شديد للتنقل.',
    'crisis.active': 'المحاكاة نشطة',
    'crisis.transport.desc': 'انهيار التنقل',
    'crisis.delivery.desc': 'طفرة الخدمات الأساسية',
    'crisis.freelance.desc': 'انتقال العمل عن بعد',
    // Google Trends
    'nav.trends': 'مؤشرات جوجل',
    'trends.title': 'رؤى مؤشرات جوجل',
    'trends.subtitle': 'تحليل اتجاهات البحث في الوقت الفعلي لكلمات اقتصاد العمل الحر عبر مؤشرات جوجل.',
    'trends.settings': 'الإعدادات',
    'trends.run': 'تشغيل التحليل',
    'trends.running': 'جاري التحليل...',
    'trends.keywords': 'الكلمات المفتاحية',
    'trends.addKeyword': 'أضف كلمة مفتاحية...',
    'trends.region': 'المنطقة الجغرافية',
    'trends.timeRange': 'النطاق الزمني',
    'trends.progressNote': 'يستغرق التحليل عادةً 2-5 دقائق. يقوم المحلل بجلب البيانات من مؤشرات جوجل.',
    'trends.error': 'فشل التحليل',
    'trends.lastUpdated': 'آخر تحديث',
    'trends.keywordsAnalyzed': 'كلمات تم تحليلها',
    'trends.noData': 'لا توجد بيانات متاحة',
    'trends.empty.title': 'لا توجد نتائج تحليل بعد',
    'trends.empty.desc': 'قم بتكوين الكلمات المفتاحية، واختر المنطقة، ثم شغّل التحليل لرؤية بيانات مؤشرات جوجل الحقيقية لأنماط البحث في اقتصاد العمل الحر.',
    'trends.configureAndRun': 'تكوين وتشغيل التحليل',
    'trends.tab.scores': 'درجات الاتجاه',
    'trends.tab.regions': 'أعلى المناطق',
    'trends.tab.queries': 'أعلى الاستعلامات',
    'trends.tab.rising': 'الاستعلامات الصاعدة',
    'trends.tab.intent': 'نية العمل',
    'trends.scores.title': 'درجات اتجاه الكلمات المفتاحية',
    'trends.scores.desc': 'متوسط مؤشر اهتمام البحث (0-100) لكل كلمة مفتاحية.',
    'trends.scores.label': 'درجة الاتجاه',
    'trends.scores.table': 'التصنيفات',
    'trends.regions.title': 'الاهتمام حسب المنطقة',
    'trends.regions.desc': 'توزيع اهتمام البحث عبر المناطق الفرعية.',
    'trends.regions.allKeywords': 'جميع الكلمات المفتاحية',
    'trends.regions.keyword': 'الكلمة المفتاحية',
    'trends.regions.regionName': 'المنطقة',
    'trends.regions.score': 'الدرجة',
    'trends.queries.title': 'أعلى الاستعلامات ذات الصلة',
    'trends.queries.desc': 'أكثر استعلامات البحث ذات الصلة شيوعاً.',
    'trends.queries.keyword': 'الكلمة المفتاحية',
    'trends.queries.query': 'الاستعلام ذو الصلة',
    'trends.queries.score': 'الدرجة',
    'trends.rising.title': 'الاستعلامات الصاعدة والمتفجرة',
    'trends.rising.desc': 'الاستعلامات التي شهدت أكبر زيادة في تكرار البحث.',
    'trends.rising.keyword': 'الكلمة المفتاحية',
    'trends.rising.query': 'الاستعلام الصاعد',
    'trends.rising.growth': 'النمو',
    'trends.intent.title': 'تحليل نية العمل من جوجل',
    'trends.intent.desc': 'تقييم نية مركب يعتمد على حجم البحث وعمق الاستعلامات ذات الصلة.',
    'trends.intent.keyword': 'الكلمة المفتاحية',
    'trends.intent.searchResults': 'نقاط بيانات البحث',
    'trends.intent.relatedCount': 'الاستعلامات ذات الصلة',
    'trends.intent.score': 'درجة النية',
    'trends.intent.topRelated': 'أعلى الاستعلامات ذات الصلة',
    'trends.intent.scoreChart': 'درجة النية حسب الكلمة المفتاحية',
    'trends.intent.relatedChart': 'عدد الاستعلامات ذات الصلة حسب الكلمة المفتاحية',
    // KPI Cards
    'trends.kpi.topKeyword': 'أعلى كلمة مفتاحية رائجة',
    'trends.kpi.searchIndex': 'مؤشر اهتمام البحث',
    'trends.kpi.topRegion': 'المنطقة المهيمنة',
    'trends.kpi.aggregateScore': 'درجة الاهتمام الإجمالية',
    'trends.kpi.risingSignals': 'إشارات صاعدة',
    'trends.kpi.noBreakout': 'لم يتم اكتشاف استعلامات متفجرة',
    'trends.kpi.highestIntent': 'أعلى نية عمل',
    'trends.kpi.intentScore': 'درجة نية مركبة',
    // Auto Insights
    'trends.keyInsights': 'رؤى رئيسية',
    'trends.insight.dominant': 'البحث المهيمن',
    'trends.insight.dominantDesc': 'تتصدر جميع الكلمات بمؤشر اهتمام بحث',
    'trends.insight.breakout': 'تنبيه انفجاري',
    'trends.insight.breakoutDesc': 'استعلامات متفجرة مكتشفة — إشارات نمو سريعة:',
    'trends.insight.regional': 'نقطة ساخنة إقليمية',
    'trends.insight.regionalDesc': 'تظهر أعلى نشاط بحث إجمالي عبر جميع الكلمات المفتاحية المتتبعة.',
    'trends.insight.intent': 'قائد نية العمل',
    'trends.insight.intentDesc': 'تظهر أعلى درجة نية عمل مركبة بقيمة',
    'trends.insight.coverage': 'تغطية التحليل',
    'trends.insight.coverageDesc1': 'كلمات متتبعة',
    'trends.insight.coverageDesc2': 'استعلامات ذات صلة',
    'trends.insight.coverageDesc3': 'مناطق فرعية نشطة',
    // App Store
    'nav.appstore': 'تحليلات المتاجر',
    'apps.title': 'رؤى متجر التطبيقات و جوجل بلاي',
    'apps.subtitle': 'تحليلات منصات اقتصاد العمل الحر في الوقت الفعلي من تقييمات المتاجر.',
    'apps.fetch': 'جلب بيانات المتاجر',
    'apps.fetching': 'جاري الجلب...',
    'apps.loading': 'جاري الجلب من App Store و Google Play...',
    'apps.loadingDesc': 'الاستعلام من iTunes و Google Play لعدد التقييمات.',
    'apps.params.title': 'معاملات التقدير',
    'apps.params.reviewRate': 'نسبة كتابة التقييم (%)',
    'apps.params.ordersPerDriver': 'متوسط الطلبات / سائق / يوم',
    'apps.params.activeRatio': 'نسبة السائقين النشطين (%)',
    'apps.params.disclaimer': 'التقديرات مبنية على افتراضات قابلة للتعديل — لا تُستخدم كأرقام رسمية دون التحقق.',
    'apps.empty.ios': 'عدد تقييمات iOS من iTunes Lookup API',
    'apps.empty.android': 'عدد تقييمات Android من Google Play',
    'apps.empty.estimation': 'تقدير السائقين',
    'apps.empty.estimationDesc': 'تقدير السائقين النشطين باستخدام معاملات قابلة للتعديل',
    'apps.empty.desc': 'اضغط جلب بيانات المتاجر لسحب عدد التقييمات الحية وتوليد تقديرات القوى العاملة.',
    'apps.kpi.totalReviews': 'إجمالي التقييمات',
    'apps.kpi.acrossStores': 'عبر جميع المنصات',
    'apps.kpi.activeDrivers': 'السائقون النشطون (تقدير)',
    'apps.kpi.atRatio': 'بمعدل نشاط',
    'apps.kpi.topPlatform': 'المنصة الأكبر',
    'apps.kpi.marketShare': 'من إجمالي التقييمات',
    'apps.kpi.iosShare': 'متوسط حصة iOS',
    'apps.kpi.iosDesc': 'للمنصات ذات بيانات iOS',
    'apps.chart.reviewsByPlatform': 'التقييمات حسب المنصة',
    'apps.chart.reviewsByPlatformDesc': 'توزيع تقييمات iOS مقابل Android لكل تطبيق.',
    'apps.chart.activeDrivers': 'تقدير السائقين النشطين',
    'apps.chart.activeDriversDesc': 'تقدير القوى العاملة لكل منصة.',
    'apps.chart.reviewDist': 'توزيع التقييمات',
    'apps.chart.reviewDistDesc': 'حصة التقييمات الكلية عبر منصات العمل الحر.',
    'apps.keyInsights': 'رؤى رئيسية',
    'apps.insight.leader': 'المنصة الرائدة',
    'apps.insight.leaderDesc': 'تتصدر بـ',
    'apps.insight.reviews': 'تقييم',
    'apps.insight.share': 'حصة سوقية',
    'apps.insight.android': 'هيمنة Android',
    'apps.insight.androidDesc': 'منصات لديها تقييمات Android أكثر من iOS',
    'apps.insight.ios': 'تواجد iOS',
    'apps.insight.iosDesc': 'متوسط حصة iOS عبر المنصات',
    'apps.insight.iosApps': 'منصات لديها بيانات iOS',
    'apps.insight.workforce': 'تقدير القوى العاملة',
    'apps.insight.workforceDesc': 'إجمالي العمالة التقديرية النشطة:',
    'apps.insight.activeDrivers': 'عبر جميع المنصات',
    'apps.table.title': 'بيانات المنصات',
    'apps.table.desc': 'تفاصيل عدد التقييمات وتقديرات السائقين لكل منصة.',
    'apps.table.app': 'المنصة',
    'apps.table.total': 'الإجمالي',
    'apps.table.transactions': 'المعاملات التقديرية',
    'apps.table.drivers': 'السائقون التقديريون',
    'apps.table.active': 'النشطون',
    'apps.table.totals': 'المجاميع',
    // AI Analyst & Widget
    'nav.aianalyst': 'محلل الذكاء الاصطناعي',
    'ai.title': 'محلل السياسات بالذكاء الاصطناعي',
    'ai.subtitle': 'اسأل عن بيانات اقتصاد العمل الحر، اتجاهات السوق، والتأثيرات على السياسات.',
    'nav.salla': 'التجارة الإلكترونية (سلة)',
    'salla.title': 'نظام التجارة الإلكترونية البيئي (سلة)',
    'salla.subtitle': 'مراقبة نمو المتاجر وحالة التسجيلات التجارية.',
    'ai.chat.placeholder': 'اسألني عن أي شيء يخص اقتصاد العمل الحر السعودي...',
    'ai.chat.send': 'إرسال',
    'ai.chat.typing': 'الذكاء الاصطناعي يفكر...',
    'ai.widget.title': 'المساعد الذكي',
    'ai.error': 'فشل الاتصال مع الذكاء الاصطناعي.',
    'nav.aqar': 'عقار إنسايتس',
    'aqar.title': 'نظام عقار الذكي: رؤى إير بي إن بي في السعودية',
    'aqar.subtitle': 'تحليلات استراتيجية لقوائم التأجير قصير المدى في المملكة.',
    'aqar.kpi.listings': 'إجمالي الوحدات',
    'aqar.kpi.hosts': 'إجمالي المضيفين',
    'aqar.kpi.superhosts': 'نسبة المضيفين المميزين',
    'aqar.kpi.avgPrice': 'متوسط سعر الليلة',
    'aqar.sync': 'مزامنة البيانات',
    // Maroof Registry
    'nav.maroof': 'سجل معروف',
    'maroof.title': 'نظام سجل معروف الذكي',
    'maroof.subtitle': 'تحليلات المتاجر الإلكترونية المسجلة في وزارة التجارة.',
    'maroof.sync': 'مزامنة البيانات',
    'maroof.kpi.totalStores': 'إجمالي المتاجر',
    'maroof.kpi.goldStores': 'ذهبية (سجل تجاري)',
    'maroof.kpi.silverStores': 'فضية (عمل حر)',
    'maroof.kpi.avgRating': 'متوسط التقييم',
    'maroof.chart.categories': 'توزيع الفئات',
    'maroof.chart.categoriesSub': 'عدد المتاجر حسب نوع النشاط',
    'maroof.chart.certification': 'توزيع الشهادات',
    'maroof.chart.certificationSub': 'ذهبية مقابل فضية',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
